service: test-apig-endpoints # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs4.3

custom:
  defaultStage: dev
  defaultRegion: us-east-1
  region: ${opt:region, self:custom.defaultRegion}
  stage: ${opt:stage, self:custom.defaultStage}

package:
  exclude:
    - src/**
    - event.json

functions:
  res200:
    handler: lib/functions/200.default
    events:
      - http:
          path: 200/post
          method: post
      - http:
          path: 200/get
          method: get
  res500:
    handler: lib/functions/500.default
    events:
      - http:
          path: 500/post
          method: post
      - http:
          path: 500/get
          method: get
